name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.config.name }}

    strategy:
      fail-fast: false

      matrix:
        config:
          - name: Windows
            os: windows-latest
            target: Win64

          - name: macOS
            os: macos-latest
            target: MacOS

          - name: Android32
            os: ubuntu-latest
            target: Android32

          - name: Android64
            os: ubuntu-latest
            target: Android64

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode Mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v3.1.0
          cli: v3.8.0
          target: ${{ matrix.config.target }}
          combine: true

  package:
    name: Package Mod

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Combine builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: combine

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infiNite-mod
          path: ${{ steps.combine.outputs.build-output }}
